vec<-c(10,20,30,40,50)
print("vector")
print(vec)
my_list<-list(name="Pooja",age=20,marks=c(80,85,90))
print("list:")
print(my_list)
mat<-matrix(1:9,nrow =3,ncol=3)
print("matrix:")
print(mat)
arr<-array(1:2,dim=c(2,3,2))
print("array:")
print(arr)
df<-data.frame(Name=c("pooja","priya","suma"),
              age=c(21,22,23),
              marks=c(85,90,95))
print("dataframe:")
print(df)
gender<-factor(c("male","female","male","female","male"))
print("factor:")
print(gender)
print("levels in factor")
print(levels(gender))
