numbers <- c(2, 4, 6, 8, 10)
cat("Cumulative Sum:\n")
print(cumsum(numbers))
cat("\nCumulative Product:\n")
print(cumprod(numbers))
cat("\nMinimum value:\n")
print(min(numbers))
cat("\nMaximum value:\n")
print(max(numbers))
