v1=c(2,4,6)
v2=c(1,3,5)
cat("Vector v1:",v1,"\n")
cat("Vector v2:",v2,"\n")
cat("v1+v2=",v1+v2,"\n")
cat("v1-v2=",v1-v2,"\n")
cat("2*v1=",2*v1,"\n")
cat("v1*v2=",v1*v2,"\n")
cat("v1/v2=",v1/v2,"\n")
A=matrix(c(1,2,3,4,5,6),nrow=2,byrow=TRUE)
B=matrix(c(6,5,4,3,2,1),nrow=2,byrow=TRUE)
cat("Matrix A:\n")
print(A)
cat("Matrix B:\n")
print(B)
cat("\n")
cat("A+B:\n")
print(A+B)
cat("A-B:\n")
print(A-B)
cat("3*A:\n")
print(3*A)
cat("A*B:\n")
print(A*B)
cat("Transpose of A:\n")
print(t(A))
