students=c("sakshi","puu","rakshu","geeta")
marks=c(85,94,56,49)
age=c(21,22,23,24)
grades=c("A","A+","B","B+")
barplot(marks,names.arg=students,col="blue",main="marks of students",ylab="marks")
plot(marks,type="o",col="blue",xlab="students",ylab="marks",main="linechartofmarks")
lines(marks,col="red",lty=2)
hist(marks,breaks=5,col="orange",main="Histogram of marks",xlab="marks",ylab="frequently")
pie(marks,labels="students",main="pie chart of marks",col=rainbow(length(marks)))
boxplot(marks,main="boxplot of marks",col="green",ylab="marks")
plot(age,marks,type="p",main="scatter plot for age vs marks",xlab="age",ylab="marks",col="purple",pch=19)
